version: "3.8"

services:
  travelog:
    image: sjw7324/travelog:latest
    container_name: travelog
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true
